version: '3.8'
services:
  signalflow-preprocessing:
    image: cincibrainlab/signalflow-datascience:cpu
    #image: cincibrainlab/signalflow-datascience:gpu
    container_name: ${CONTAINER_NAME}
    environment:
      - JUPYTER_TOKEN=password
      - VNC_PW=password
      - MLM_LICENSE_FILE=/licenses/license.lic
      - HOST=P16-4023
      - STUDENT_USER=${STUDENT_USER}
    hostname: P16-4023
    mac_address: ${MAC_ADDRESS}
    ports:
      - "${WEB_PORT}:6901"
    volumes:
      - ${LOCAL_FOLDER}:/srv
      - ${MATLAB_LICENSE_FILE}:/licenses/license.lic
    shm_size: 16gb
    working_dir: /srv

