version: '3.8'
services:
  app:
    container_name: ${CONTAINER_NAME}
    image: ${IMAGE_NAME}
    shm_size: '512M'
    volumes:
      - '..:/workspace:cached'
      - '${MATLAB_LICENSE_FILE}:/licenses/license.lic'
      - '${STORAGE_FOLDER}:/srv'
      - '${DROPBOX_FOLDER}:/srv/Dropbox'
      - '${HOME_FOLDER}:/srv/Home'
    hostname: ${HOSTNAME}
    mac_address: ${MAC_ADDRESS}
    user: root
    deploy:
      resources:
        limits:  # Add the limits section
          cpus: ${CPU_LIMIT}  # Limit the CPU usage. Value should be in format '0.01', '0.1', '1', etc.
          memory: ${MEM_LIMIT}G  # Limit the memory usage. Value is in gigabytes.
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - MLM_LICENSE_FILE=/licenses/license.lic
      - HOST=${HOSTNAME}
      - NB_USER=${NB_USER}
      - JUPYTER_TOKEN=${PASSWORD} 
      - CHOWN_HOME=yes
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    working_dir: /home/${NB_USER} 
    ports:
      - ${WEB_PORT}:8888
    command: >
      bash -c '
      printf "${NB_USER} ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/$${NB_USER} &&
      exec start-notebook.sh'
