version: '3.8'
services:
  sf-dev01:
    image: cincibrainlab/signalflow-development:jammy
    container_name: sf-dev01
    environment:
      - VNC_PW=password
      - START_XFCE4=1
      - MLM_LICENSE_FILE=/licenses/license.lic
      - HOST=${HOSTNAME}
      - NB_USER=${NB_USER}
      - JUPYTER_TOKEN=${PASSWORD} 
      - CHOWN_HOME=yes
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - '..:/workspace:cached'
    hostname: ${HOSTNAME}
    mac_address: ${MAC_ADDRESS}
    ports:
      - "${WEB_PORT}:6901"
    volumes:
      - ${LOCAL_STORAGE}:/srv
      - ${CERTS_DIR}:/usr/local/share/ca-certificates/
    shm_size: 512m
    working_dir: /srv
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: >
      bash -c '
      sudo update-ca-certificates &&
      --tail-log'
